services:
  - type: web  # or "worker"
    name: discord-bot
    env: python
    plan: free
    autoDeploy: true
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: DISCORD_TOKEN
        value: YOUR_BOT_TOKEN
